/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exercice2nom;

/**
 *
 * @author jerem
 */
public class CALCUL_JAVA extends javax.swing.JFrame {

    /**
     * Creates new form CALCUL_JAVA
     */
    public CALCUL_JAVA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNbre1 = new javax.swing.JTextField();
        txtNbre2 = new javax.swing.JTextField();
        btnDIFF = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbOperateur = new javax.swing.JComboBox<>();
        btnDIVI = new javax.swing.JButton();
        btnSOMME = new javax.swing.JButton();
        btnPLUS = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtResultat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 153));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel5.setText("LA CALCULATRISE JM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setText("Choissisez Nbre 1 :");
        jLabel1.setFocusCycleRoot(true);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setText("Choissisez Nbre 2 :");

        txtNbre1.setName("txtNbre1"); // NOI18N

        txtNbre2.setName("txtNbre2"); // NOI18N

        btnDIFF.setBackground(new java.awt.Color(255, 255, 0));
        btnDIFF.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnDIFF.setText("-");
        btnDIFF.setName("btnCal"); // NOI18N
        btnDIFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDIFFActionPerformed(evt);
            }
        });

        btnClean.setBackground(new java.awt.Color(51, 51, 255));
        btnClean.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnClean.setText("CLEAN");
        btnClean.setName("btnClean"); // NOI18N
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setText("Choissisez L'operateur:");

        cmbOperateur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner l'operateur", "ADDICTION (+)", "SOUSTRACTION (-)", "MULTIPLICATION (*)", "DIVISION (/)" }));
        cmbOperateur.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOperateurItemStateChanged(evt);
            }
        });
        cmbOperateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOperateurActionPerformed(evt);
            }
        });

        btnDIVI.setBackground(new java.awt.Color(0, 153, 153));
        btnDIVI.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnDIVI.setText("/");
        btnDIVI.setName("btnCal"); // NOI18N
        btnDIVI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDIVIActionPerformed(evt);
            }
        });

        btnSOMME.setBackground(new java.awt.Color(255, 0, 51));
        btnSOMME.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnSOMME.setText("+");
        btnSOMME.setName("btnCal"); // NOI18N
        btnSOMME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSOMMEActionPerformed(evt);
            }
        });

        btnPLUS.setBackground(new java.awt.Color(0, 255, 0));
        btnPLUS.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnPLUS.setText("*");
        btnPLUS.setName("btnCal"); // NOI18N
        btnPLUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPLUSActionPerformed(evt);
            }
        });

        btnOK.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnOK.setText("OK");
        btnOK.setName("btnCal"); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbOperateur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNbre1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNbre2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnSOMME, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDIFF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPLUS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDIVI, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnClean)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNbre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNbre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbOperateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClean)
                    .addComponent(btnDIVI)
                    .addComponent(btnDIFF)
                    .addComponent(btnSOMME)
                    .addComponent(btnPLUS)
                    .addComponent(btnOK))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setText("RESULTAT");

        txtResultat.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txtResultat.setName("txtResultat"); // NOI18N
        txtResultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(txtResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDIFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDIFFActionPerformed
        int Nbre1 = Integer.parseInt(txtNbre1.getText());
        int Nbre2 = Integer.parseInt(txtNbre2.getText());
        
        txtResultat.setText("La difference est : " + (Nbre1 - Nbre2));        // TODO add your handling code here:
    }//GEN-LAST:event_btnDIFFActionPerformed

    private void txtResultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultatActionPerformed

    private void btnDIVIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDIVIActionPerformed
        int Nbre1 = Integer.parseInt(txtNbre1.getText());
        int Nbre2 = Integer.parseInt(txtNbre2.getText());
        if (Nbre2 ==0 ){
        txtResultat.setText("Nombre 2 doit etre != 0");         // TODO add your handling code here:
    }//GEN-LAST:event_btnDIVIActionPerformed
        else{
            txtResultat.setText(" Le quotient est : " + (Nbre1 / Nbre2));
        }}
    private void btnSOMMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSOMMEActionPerformed
        int Nbre1 = Integer.parseInt(txtNbre1.getText());
        int Nbre2 = Integer.parseInt(txtNbre2.getText());
        
        txtResultat.setText("La somme est : " + (Nbre1 + Nbre2));         // TODO add your handling code here:
    }//GEN-LAST:event_btnSOMMEActionPerformed

    private void btnPLUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPLUSActionPerformed
        int Nbre1 = Integer.parseInt(txtNbre1.getText());
        int Nbre2 = Integer.parseInt(txtNbre2.getText());
        
        txtResultat.setText("Le produit est : " + (Nbre1 * Nbre2));         // TODO add your handling code here:
    }//GEN-LAST:event_btnPLUSActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        txtNbre1.setText("");
        txtNbre2.setText("");
        txtResultat.setText("");
        cmbOperateur.setSelectedIndex(0); 
                  // TODO add your handling code here:
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        double Nbre1 = Integer.parseInt(txtNbre1.getText());
        double Nbre2 = Integer.parseInt(txtNbre2.getText());
        
        if( cmbOperateur.getSelectedIndex()==1) {
           txtResultat.setText("Le Somme est : " + (Nbre1 + Nbre2));
        } else{
            if(cmbOperateur.getSelectedIndex()==2){
                txtResultat.setText("La difference est : " + (Nbre1 - Nbre2));
            } else{
               if(cmbOperateur.getSelectedIndex()==3){
                txtResultat.setText("Le produit est : " + (Nbre1 * Nbre2));
            }        else{
                          if(cmbOperateur.getSelectedIndex()==4){
                               txtResultat.setText("La quotient est : " + (Nbre1 / Nbre2));
                           }  
            }
        }
                
    }
    }//GEN-LAST:event_btnOKActionPerformed

    private void cmbOperateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOperateurActionPerformed

    private void cmbOperateurItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOperateurItemStateChanged
       double Nbre1 = Integer.parseInt(txtNbre1.getText());
        double Nbre2 = Integer.parseInt(txtNbre2.getText());
        
        if( cmbOperateur.getSelectedIndex()==1) {
           txtResultat.setText("Le Somme est : " + (Nbre1 + Nbre2));
        } else{
            if(cmbOperateur.getSelectedIndex()==2){
                txtResultat.setText("La difference est : " + (Nbre1 - Nbre2));
            } else{
               if(cmbOperateur.getSelectedIndex()==3){
                txtResultat.setText("Le produit est : " + (Nbre1 * Nbre2));
            }        else{
                          if(cmbOperateur.getSelectedIndex()==4){
                               txtResultat.setText("La quotient est : " + (Nbre1 / Nbre2));
                           }  
            }
        }
                
    }       // TODO add your handling code here:
    }//GEN-LAST:event_cmbOperateurItemStateChanged
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CALCUL_JAVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CALCUL_JAVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CALCUL_JAVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CALCUL_JAVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CALCUL_JAVA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnDIFF;
    private javax.swing.JButton btnDIVI;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPLUS;
    private javax.swing.JButton btnSOMME;
    private javax.swing.JComboBox<String> cmbOperateur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtNbre1;
    private javax.swing.JTextField txtNbre2;
    private javax.swing.JTextField txtResultat;
    // End of variables declaration//GEN-END:variables
}
